include $(THEOS)/makefiles/common.mk
APPLICATION_NAME = GPTAssistant
GPTAssistant_FILES = main.m ChatViewController.m
GPTAssistant_FRAMEWORKS = UIKit Foundation
GPTAssistant_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/application.mk
